name: Typedoc

on:
  push:
    branches: [ "main" ]

jobs:
  docs:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn typedoc
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: doc
